export const ACTIONS = {
  GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR',
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_SHOPPING_CARD',
  REFRESH_PRODUCT_CART: 'REFRESH_PRODUCT_CART',
  REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_TO_SHOPPING_CARD',
  CONFIRM_ERROR: 'CONFIRM_ERROR',
  SET_PRODUCT_CART_QUANTITY: 'SET_PRODUCT_CART_QUANTITY',
};

export const CART_KEY = 'SHOPPING_CART';